name: PR Test

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Hi this is Surya"
          echo "All tests passed!"
